# 当药水效果持续时间已过时是否重新设置
# 由于1.12.2无法直接支持, 实现较为复杂, 暂时不做
reapply: true
# 是否在插件关闭时清除此插件对玩家设置的药水效果
clear: true
# 是否开启调试模式, 启用调试模式提示消息会增多, 可能刷屏
debug: false
# 世界列表, 意义自行体会, effect值为药水效果名或其id
worldList:
  world:
    effect: jump
    # 药水效果倍数
    amplifier: 1
    # 药水效果持续时间, 默认为无限
    duration: 1000000